first_integer_variable = 5
this_is_a_string_variable = "my string"
integer_2nd_variable = 4
float_variable_number_1 = 4.5
float_variable_number_2 = 5.3
adding_integers = first_integer_variable + integer_2nd_variable
substraction_result_of_float_numbers = float_variable_number_1-float_variable_number_2
multiplication_of_2_numbers = first_integer_variable*float_variable_number_1
division_of_2_numbers = float_variable_number_2/integer_2nd_variable
mod_of_a_division = first_integer_variable % integer_2nd_variable
doubleDivision = first_integer_variable/integer_2nd_variable
exponentialOperator =  float_variable_number_1**float_variable_number_2

print("addition: ", first_integer_variable,'+',integer_2nd_variable,'=', adding_integers)
print("substraction:", float_variable_number_1,'-',float_variable_number_2,'=', substraction_result_of_float_numbers)
print("multiplication: ", first_integer_variable,'*', float_variable_number_1, ' = ', multiplication_of_2_numbers)
print("division: ", float_variable_number_2,'/', integer_2nd_variable,' = ', division_of_2_numbers)
print("mod: ", first_integer_variable, '%', integer_2nd_variable,' = ', mod_of_a_division)
print("// operator: ", first_integer_variable, '//', integer_2nd_variable,' = ', doubleDivision)
print("** operator: ", float_variable_number_1, '**', float_variable_number_2,' = ', exponentialOperator)