# This OAuth 2.0 access scope allows for full read/write access to the
# authenticated user's account.
APP:
  ENDPOINT: https://www.googleapis.com/
  YOUTUBE_API_ROOTPATH: youtube/v3


USERS:
  USER_MAURICIO: ramadantis
  API_KEY_MAURICIO: AIzaSyAD9cHpwwD_rQtsveLv7AJ5BeobmPkx21E
  USER_ALEJANDRO: slevin
  API_KEY_ALEJANDRO: AIzaSyCcuxtUYUAnquyWP_oDYeC9J4wucaD_PWo
  USER_DENNIS: Kalulas
  API__KEY_DENNIS: AIzaSyA6uebn-2eWq6_jQT8KEbRDix5zKmto9K8
  USER_PABLO: pzytapi1
  API__KEY_PABLO: AIzaSyAWrxEnAhL_mz89M2jWID6jzulSA5cqxck
  USER_DANEIVA: Daneiva
  API__KEY_DANEIVA: AIzaSyAdbQ1hnwmA4wTTvHsS_HD1zrWceryrQeM